name: Bug Report
description: Report a bug in the app
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Please attach or paste logs from the `/Logs/` folder if available."
      placeholder: "Paste logs here or drag-and-drop the file"
