body:
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Please attach or paste logs from the `/Logs/` folder if available."
      placeholder: "Paste logs here or drag-and-drop the file"